### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by droxey** [kevin-meyers/level-2-kits#2]
**FEEDBACK**: 

- [x] Please use the standard `requirements.txt` to distribute dependencies rather than `pipenv`. Pipenv requires another executable to be installed on the local machine.
- [x] Incomplete `dotenv` integration. See `django-dotenv` for the proper way to handle hiding secrets.

| Criteria                                                               | Possible  |     ✓    |
| -------------------------------------------- | :-------:  | :-----: |
| At least 2 apps in project                                 |   `40`    |   `40`   | 
| At least 2 tests in `tests.py` in each app       |   `30`    |   `25`   | 
| Modular design                                                 |   `25`    |   `25`   |
| RESTful API using Django REST Framework  |   `25`    |   `0`   |
| Template-based front-end interface              |   `25`    |   `25`   |
| Has purpose & fulfills proposal                       |   `20`    |   `20`   |
| Integrates an open source app                       |   `20`    |   `0`   |
| Deployed & usable                                           |   `15`    |   `15`   |
| Includes database migrations in each app    |   `15`    |   `15`   |
| `README` with documentation                     |   `10`    |   `10`   |
| Public GitHub repo                                          |    `5`    |   `5`    | 
| **TOTAL**                                                         | **`230`** | **`180`** |

**Comment by kevin-meyers** [comment]
Removed ```- [ ] Tests fail due to incorrect syntax and cannot be run. Tests should not break if they are incomplete!```
from the issue to put in a separate one.

**Comment by kevin-meyers** [comment]
Thank you for teaching me this semester Dani! I am going to take this project to the next level over break and in this intensive. I plan on building it into my first portfolio site and hopefully make it into a real thing!
